post_install(){

cat << EOF

=========
Phing will be dropping support for manual installation as of version 3.0.

It is recommended that you migrate your dependencies to
Composer (http://getcomposer.org).
=========

EOF

}

post_upgrade(){

cat << EOF

=========
Phing will be dropping support for manual installation as of version 3.0.

It is recommended that you migrate your dependencies to
Composer (http://getcomposer.org).
=========

EOF

}
